version: "3.9"

services:
  dev:
    build: 
      context: .
    depends_on:
      - db
    environment:
      - PORT=8000
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=secret
      - PG_DB_NAME=tests
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
